(deftheme mpi
  "Created 2020-11-18.")

(custom-theme-set-faces
 'mpi
 '(vertical-border ((t (:foreground "gray"))))
 '(cursor ((t (:background "lime green"))))
 '(bold ((t (:weight bold))))
 '(bold-italic ((t (:weight bold :slant italic))))
 '(custom-face-tag ((t (:foreground "#66D9EF" :weight bold))))
 '(custom-state ((t (:foreground "#BB98FC"))))
 '(italic ((t (:slant italic))))
 '(region ((t (:background "SteelBlue4"))))
 '(underline ((t (:underline t))))
 '(diff-context ((t (:foreground "#E8F0FF"))))
 '(diff-file-header ((t (:foreground "#66D9EF" :background nil))))
 '(diff-header ((t (:foreground "#E8F0FF" :background "#232526"))))
 '(diff-hunk-header ((t (:foreground "#A6E22E" :background "#232526"))))
 '(diff-refine-added ((t (:foreground "#A6E22E"))))
 '(diff-refine-changed ((t (:foreground "#5FCA81"))))
 '(diff-refine-removed ((t (:foreground "#D2527F"))))
 '(diff-added ((t (:foreground "#A6E22E"))))
 '(diff-changed ((t (:foreground "#5FCA81"))))
 '(diff-removed ((t (:foreground "#D2527F"))))
 '(diff-indicator-added ((t (:foreground "#A6E22E"))))
 '(diff-indicator-changed ((t (:foreground "#5FCA81"))))
 '(diff-indicator-removed ((t (:foreground "#D2527F"))))
 '(escape-glyph ((t (:foreground "#C1CAFF"))))
 '(minibuffer-prompt ((t (:foreground "#66D9EF"))))
 '(mode-line ((t (:background "lime green" :foreground "black" :box nil))))
 '(mode-line-inactive ((t (:background "#1d2130" :foreground "gray" :box nil))))
 '(font-lock-builtin-face ((t (:foreground "#BB98FC"))))
 '(font-lock-comment-face ((t (:foreground "#6F7181" :slant normal))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#6F7181" :slant normal))))
 '(font-lock-constant-face ((t (:foreground "#A6E22E"))))
 '(font-lock-doc-face ((t (:foreground "#C1CAFF" :slant normal))))
 '(font-lock-function-name-face ((t (:foreground "#84B5FF" :slant normal))))
 '(font-lock-keyword-face ((t (:foreground "#66D9EF"))))
 '(font-lock-negation-char-face ((t (:weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#BB98FC"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold))))
 '(font-lock-string-face ((t (:foreground "#C1CAFF"))))
 '(font-lock-type-face ((t (:foreground "#66D9EF" : normal slant))))
 '(font-lock-variable-name-face ((t (:foreground "#5FCA81"))))
 '(font-lock-warning-face ((t (:foreground "#FFFFFF" ':background "#333333"))))
 '(success ((t (:foreground "#BB98FC"))))
 '(highlight ((t (:foreground "#000000" :background "#C1CAFF"))))
 '(lazy-highlight ((t (:foreground "#000000" :background "#C1CAFF"))))
 '(isearch ((t (:foreground "#000000" :background "#C1CAFF"))))
 '(isearch-fail ((t (:foreground "#FFFFFF" :background "#333333"))))
 '(outline-2 ((t (:background "#282A36" :foreground "#BB98FC"))))
 '(outline-1 ((t (:background "#282A36" :foreground "#66D9EF"))))
 '(outline-3 ((t (:background "#282A36" :foreground "#5FCA81"))))
 '(outline-4 ((t (:background "#282A36" :foreground "#A6E22E"))))
 '(outline-5 ((t (:background "#282A36" :foreground "#4577D7"))))
 '(outline-6 ((t (:background "#282A36" :foreground "#FF84C9"))))
 '(outline-7 ((t (:background "#282A36" :foreground "#FF5996"))))
 '(outline-8 ((t (:background "#282A36" :foreground "#60FCEC"))))
 '(secondary-selection ((t (:foreground "#E8F0FF"))))
 '(shadow ((t (:foreground "#6F7181"))))
 '(widget-inactive ((t (:background "#FF0000"))))
 '(widget-button-pressed ((t (:foreground "#FFCACA"))))
 '(undo-tree-visualizer-active-branch-face ((t (:inherit default))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#EF5939"))))
 '(undo-tree-visualizer-default-face ((t (:inherit shadow))))
 '(undo-tree-visualizer-register-face ((t (:foreground "#C1CAFF"))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "#66D9EF"))))
 '(ivy-current-match ((t (:background "#4577D7" :foreground "#FFFFFF"))))
 '(ivy-highlight-face ((t (:background "#000000" :foreground "#5FCA81"))))
 '(ivy-modified-buffer ((t (:inherit default :foreground "#FD971F"))))
 '(ivy-virtual ((t (:inherit default))))
 '(ivy-minibuffer-match-face-1 ((t (:inherit default :foreground "#A6E22E"))))
 '(ivy-minibuffer-match-face-2 ((t (:inherit default :foreground "#A6E22E"))))
 '(ivy-minibuffer-match-face-3 ((t (:inherit default :foreground "#A6E22E"))))
 '(ivy-minibuffer-match-face-4 ((t (:inherit default :foreground "#A6E22E"))))
 '(swiper-line-face ((t (:background "#4577D7" :foreground "#000000"))))
 '(swiper-match-face-2 ((t (:foreground "#84B5FF"))))
 '(ivy-modified-buffer ((t (:inherit default :foreground "#FF84C9"))))
 '(neo-dir-link-face ((t (:foreground "#84B5FF"))))
 '(neo-root-dir-face ((t (:foreground "#66D9EF"))))
 '(show-paren-match ((t (:background "#D2527F" :foreground "#000000" :weight bold))))
 '(show-paren-mismatch ((t (:background "#FF0000" :foreground "#FFFFFF"))))
 '(dired-directory ((t (:foreground "#84B5FF"))))
 '(line-number ((t (:foreground "steel blue"))))
 '(line-number-current-line ((t (:background "dim gray" :foreground "white"))))
 '(link ((t (:foreground "#60FCEC" :background "#282A36" :underline t))))
 '(markdown-header-face-1 ((t (:foreground "#84B5FF"))))
 '(markdown-header-face-2 ((t (:inherit outline-1))))
 '(markdown-header-face-3 ((t (:inherit outline-2))))
 '(markdown-header-face-4 ((t (:inherit outline-3))))
 '(markdown-header-face-5 ((t (:inherit outline-4))))
 '(markdown-header-face-6 ((t (:inherit outline-5))))
 '(default ((t (:background "#141e29" :foreground "#E8F0FF")))))

(provide-theme 'mpi)
